name: ci
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            x86-linux,
            x86_64-linux,
            aarch64-linux,
            riscv64-linux,
            x86_64-macos-gnu,
            x86_64-windows,
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master

      - name: Build
        run: zig build -Doptimize=ReleaseFast -Dtarget=${{ matrix.target }}

      - name: Archive executable
        uses: actions/upload-artifact@v3
        with:
          name: lifetch
          path: zig-out/bin/*
