name: ci

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Build
        run: zig build -Doptimize=ReleaseFast

      - name: Archive executable
        uses: actions/upload-artifact@v4
        with:
          name: lifetch
          path: zig-out/bin/*
          if-no-files-found: error
          compression-level: 6

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: lifetch
          path: lifetch-bin

      - name: Create Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release ${{ github.ref_name }}
