name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Build
        run: zig build -Doptimize=ReleaseFast

      - name: Archive executable
        uses: actions/upload-artifact@v3
        with:
          name: lifetch
          path: zig-out/bin/*
